var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                  xxx           ",
   "                                                                                ",
   "                                     o                             o            ",
   "                                          yyy                                   ",
   "                                                                                ",
   "                                               xx                x!!!x       p  ",
   "                                xxxxxxxx                         xxxxx       x  ",
   "                                   yyyyy                          xxx        x  ",
   "                                                                             x  ",
   "  xx                       s                                                 x  ",
   "  x                       xx                                             xx  x  ",
   "  x    xxx                          o                                xx      x  ",
   "  x    x     xxxx                  xxx                           xx          x  ",
   "  x  @ x    xx  x                  x x                                       x  ",
   "  xxxxxx   oxx  xxxxxxxxxxxxxxx   xx xxxxxxxxxxxxxxxxx       xxxxxxxxxxxxxxxxx  ",
   "      x    xx                 x   x                  x   o   x                  ",
   "      x     x                 x!!!x                  x!!xxx!!x                  ",
   "      x!!!!!x                 x!!!x                  x!!!!!!!x                  ",
   "      xxxxxxx                 xxxxx                  xxxxxxxxx                  ",
   "                                                                                ",
   "                                                                                "],
  ["                                                                               ",
   "                                                                               ",
   "                                                               o               ",
   "                                                              xxx              ",
   "                                                  o                            ",
   "                           s                     xxx                           ",
   "     @                            xxxxxx         xxx                           ",
   "    xxx                              v                                         ",
   "    xxx      xxx                                                       x       ",
   "    xxxxxx   x x                                      p                x       ",
   "oo  xxx      x xxxxxxxxx!!!!!xxxxxxxxxxx              xxxxxxxxxxx      x       ",
   "xx  xxx    xxx x!!!!!!!!!!!!!!!!!!!!!!xx            o xx        x   o  x       ",
   "!!!!xxx      x x!!!!!!!!!!!!!!!!!!!!!!xx      xxxxxxx xx        x      x       ",
   "!!!!xxx      x x!!!!!!!!!!!!!!!!!!!!!!xx              xx        x      x       ",
   "!!!!xxx     ox x!!!!!!!!!!!!!!!!!!!!!!xx              xx        x!!!!!!x       ",
   "!!!!xxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!xx              xx        x!!!!!!x       ",
   "                                       xx             xx        x!!!!!!x       ",
   "                                       xxxxx   o      xx        x!!!!!!x       ",
   "                                       xx!!!xxxxx   o xx        xxxxxxxx       ",
   "                                       xx!!!!!!!!xxxxxxx                       ",
   "                                       xx!!!!!!!!!!!!!xx                       ",
   "                                       xx!!!!!!!!!!!!!xx                       ",
   "                                       xx!!!!!!!!!!!!!xx                       "],
  

  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                        o                   x          x                                      ",
   "                                     xxx xxx                x          x                                      ",
   "                                      x   x                 x   oooo   x       xxx                            ",
   "                           xxxx       x   x                 x    xx    x                                      ",
   "                                                                                o                             ",
   "     x!!!x                                                                                                    ",
   "       v              xxxx            x   x                 xxxxxxxxxxxx       xxx                            ",
   "                                     xx   xx       x               x                                          ",
   "                                              xxxxxx!!!!!!!!!!!!!!xxx                                         ",
   "                                          x   xxxxxxxxxxxxxxxxxxxxxxx                                         ",
   "   @                          xxxxxx       xx                                        xxx                      ",
   "  xxx                         x o  x      x                                         x!!!x                xxx  ",
   "  x x                         x    x      xo                                         x!x                 x x  ",
   "  x                           x    x      xxxxxxx                        xxxxx                           V x  ",
   "  x   xxxx                    x    xxxx        x                              x   x                        x  ",
   "  x                           xx      x    x                              x x x       o                    x  ",
   "  x                      o            x    x       |xxxx|    |xxxx|     xxx xxx                            x  ",
   "  x        xxxxx        xxx           x o o    x                              x      xxx                   x  ",
   "  x          v           xx     o     x                            xxx       x!!!x          x                 ",
   "  x                       x    xxx    x                             x x        xxx          xxx               ",
   "  x               xxxxx                                                                                       ",
   "  x  o                                                                                                   o    ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                xxxxxxxxxxx                             xxxx                                  ",
   "                                                                                                              "],
  

  ["                                                                                                              ",
   "                                                                                                              ",
   "                                   o                                                                          ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                x                                                                             ",
   "                             o           o                                                                    ",
   "                   xxx                                                                                        ",
   "                           xxxxx xxxxx xxxxx xxxxx     xxxxx xxxxx                                            ",
   "                                                 x!!!!!x                                                      ",
   "                                                 xxx!xxx                                                      ",
   "                         xxx                        v                     xxxxxx            xxxxxx            ",
   "                          v                                                   xxxxx   p   xxxxx               ",
   "                                                                                 xxxxxxxxxx                   ",
   "                                                                                                              ",
   "                     xxx         xxx                                                                          ",
   "                                                                  o                                           ",
   "                           o                                                                            o     ",
   "                                                          xx     xx                                           ",
   "                         xxx         xxx         xxx                                                    x     ",
   "                                                                                                              ",
   "                                                        s         ||                                          ",
   "  xxxxxxxxxxx                                                                                    xx           ",
   "  x         x ! xxxxxxxxx o xxxxxxxxx o xx          xx                                                        ",
   "  x         x v x       x   x       x   x         xx                                                          ",
   "  x  @              o     o   xxxxx             xx                                                 x          ",
   "  xxxxxxx                                     xx       xx     xx     xxx                                      ",
   "        x=                                   =x   x                     xxx                                   ",
   "        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   x!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "],

  ["     xx    xx   xxxxxx   xx    xx      xx       xx  xx  xxx    xx  xx           ",
   "      xx  xx   xx    xx  xx    xx      xx       xx  xx  xx xx  xx  xx           ",
   "       xxxx    xx    xx  xx    xx      xx  xxx  xx  xx  xx  xx xx  xx           ",
   "        xx     xx    xx  xx    xx      xx xx xx xx  xx  xx   xxxx               ",
   "        xx      xxxxxx    xxxxxx        xxx   xxx   xx  xx    xxx  xx           ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                "],

];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
